apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: 2-app
  namespace: flux-system
spec:
  interval: 1m
  path: ./my-cluster/2-app
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
