apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: 1-demo
  namespace: flux-system
spec:
  interval: 1m
  path: ./flux-system/1-demo   # ðŸ‘ˆ points to your app manifests
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system   # ðŸ‘ˆ same Git source you already have
